events { }

http {
    upstream ml_backend {
        # 90% трафика на старую версию
        server ml_service_v1:8080 weight=90;

        # 10% трафика на новую canary-версию
        server ml_service_v2:8080 weight=10;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://ml_backend;
        }
    }
}
